WWW_4_2/stronka_1/jakis_polls/urls.py
from django.urls import path
from . import views

app_name = 'jakis_polls'

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('<int:question_id>/', views.question_detail, name='question_detail'),
]

WWW_4_2/stronka_1/stronka_1/urls.py
from fileinput import hook_compressed
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home_view),
    path('admin/', admin.site.urls),
    path('jakis_polls/', include('jakis_polls.urls', namespace='jakis_polls')),
]

WWW_4_2/stronka_1/jakis_polls/models.py
from django.db import models


class Question(models.Model):
    def __str__(self):
        return self.question_text
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Answer(models.Model):
    def __str__(self):
        return self.answer()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    is_open = models.BooleanField(default=True)
    answer = models.TextField(max_length=200)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    def __str__(self):
        return self.choice_text

WWW_4_2/stronka_1/jakis_polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Question

# Create your views here.
def question_list(request):
    questions = Question.objects.order_by('-question_text')
    filtered = questions.filter(pk=1)
    return render(request, 'jakis_polls/question_list.html', {'questions': filtered})

def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'jakis_polls/question_list.html', {'question': question})

WWW_4_2/stronka_1/stronka_1/views.py
from django.shortcuts import render, get_object_or_404
def home_view(request):
    return render(request, 'home.html')

WWW_4_2/stronka_1/jakis_polls/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Siema!</p>
    {% if request.user.is_authenticated %}
    <p>No siema {{ request.user.get_username }}!</p>
    {% else %}
    <p>Nie zalogowales sie</p>
    {% endif %}
    <a href="jakis_polls">Podstrona</a>
</body>
</html>

WWW_4_2/stronka_1/jakis_polls/templates/jakis_polls/question_detail.html
<!DOCTYPE html>
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} | {{ choice.votes }} | {{choice.answer}}</li>
{% endfor %}
</ul>

WWW_4_2/stronka_1/jakis_polls/templates/jakis_polls/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Questions</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'jakis_polls/styles.css' %}">
</head>
<body>
    <table style="text-align:center;">
        {% for question in questions %}
        <tr>
          <th>id</th>
          <th>text</th>
          <th>data</th>
        </tr>
        <tr>
          <td><a href="{% url 'jakis_polls:question_detail' question.id %}">{{ question.id }}</td>
          <td><a href="{% url 'jakis_polls:question_detail' question.id %}">{{ question.question_text}}</td>
          <td>{{question.pub_date }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>